Add tools to create test users with unexpired passwords
freeipa/freeipa-perftest pull request #4
Opened 2021-10-25 20:32 UTC by rcritten

create-test-data.py comes from the freeipa-tools repo. It is
designed to create complex test data including nested groups,
hbac and sudo rules. It provides way more than we need here but
we may be able to build on it.

As such, this overrides some of its methods to generate a
number of users per host with a given username format.

Whether we can mangle this into creating the other entry types in
the future is TBD but I think it is possible.

The password is 'password'.

Users are created in the form: user#client#.<domain>

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

2021-11-08 16:29 UTC, antoniotorresm requested changes

2021-11-08 16:29 UTC, antoniotorresm commented on README.md
> +In order to set passwords using a pre-hashed password IPA neesd to
typo: "neesd"

2021-11-08 16:29 UTC, antoniotorresm commented on README.md
> +./set-password.py --dm-password <Directory Manager password>
Could you add backticks so that the command is formatted? (same for the other commands).

2021-11-08 16:29 UTC, antoniotorresm commented
Apart from that, everything LGTM.

2021-11-12 13:19 UTC, rcritten commented
Thanks for the review, comments addressed.

2021-11-12 13:20 UTC, antoniotorresm approved these changes

2021-11-12 13:21 UTC, merged